import{PRESETS,WORLDS,HEROES,PRAISE}from'./data.js';
import{loadSave,saveGame}from'./storage.js';
import{roundRect,drawHero,drawStar,drawDecor}from'./art.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),wrap=$('wrap'),overlay=$('overlay'),toast=$('toast');
let save=loadSave(),cfg=PRESETS.easy,world=WORLDS[0],hero=HEROES[0],maze=[],stars=[],decor=[],particles=[],hazards=[],keyItem=null,goal={},ball={x:0,y:0,vx:0,vy:0,r:10},cell=24,ox=0,oy=0,wall=4,tilt={x:0,y:0},raw={x:0,y:0},cal={beta:0,gamma:0},running=false,done=false,last=performance.now(),drag=null,sensorSeen=false,audio=null;
function unlockedWorld(){return WORLDS.reduce((best,w)=>save.totalStars>=w.need?w:best,WORLDS[0])}function sync(){world=unlockedWorld();hero=HEROES.find(h=>h.id===save.hero&&save.totalStars>=h.need)||HEROES[0];$('level').textContent=save.level;$('totalStars').textContent=save.totalStars;$('worldName').textContent=world.name}
function tone(kind){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(kind==='win'?523:kind==='key'?660:880,n);if(kind==='win')o.frequency.exponentialRampToValueAtTime(1046,n+.45);g.gain.setValueAtTime(.09,n);g.gain.exponentialRampToValueAtTime(.001,n+.5);o.start();o.stop(n+.52)}catch{}}
function praise(text=PRAISE[Math.floor(Math.random()*PRAISE.length)]){toast.textContent=text;toast.classList.add('show');clearTimeout(praise.t);praise.t=setTimeout(()=>toast.classList.remove('show'),950)}
function generate(){maze=Array.from({length:cfg.rows},(_,y)=>Array.from({length:cfg.cols},(_,x)=>({x,y,seen:false,w:{t:1,r:1,b:1,l:1}})));let cur=maze[0][0],stack=[],seen=1,total=cfg.cols*cfg.rows;cur.seen=true;while(seen<total){let n=[],x=cur.x,y=cur.y;if(y&&!maze[y-1][x].seen)n.push(['t',maze[y-1][x]]);if(x<cfg.cols-1&&!maze[y][x+1].seen)n.push(['r',maze[y][x+1]]);if(y<cfg.rows-1&&!maze[y+1][x].seen)n.push(['b',maze[y+1][x]]);if(x&&!maze[y][x-1].seen)n.push(['l',maze[y][x-1]]);if(n.length){let[d,next]=n[Math.floor(Math.random()*n.length)];stack.push(cur);if(d==='t'){cur.w.t=0;next.w.b=0}if(d==='r'){cur.w.r=0;next.w.l=0}if(d==='b'){cur.w.b=0;next.w.t=0}if(d==='l'){cur.w.l=0;next.w.r=0}cur=next;cur.seen=true;seen++}else cur=stack.pop()}for(let i=0;i<total*.12;i++){let x=Math.floor(Math.random()*cfg.cols),y=Math.floor(Math.random()*cfg.rows);if(x<cfg.cols-1&&Math.random()<.5){maze[y][x].w.r=0;maze[y][x+1].w.l=0}else if(y<cfg.rows-1){maze[y][x].w.b=0;maze[y+1][x].w.t=0}}}
function randomCell(used){let x,y,k;do{x=Math.floor(Math.random()*cfg.cols);y=Math.floor(Math.random()*cfg.rows);k=x+','+y}while(used.has(k));used.add(k);return{x,y}}
function place(){let used=new Set(['0,0',`${cfg.cols-1},${cfg.rows-1}`]);stars=Array.from({length:cfg.stars},()=>({...randomCell(used),taken:false,p:Math.random()*7}));keyItem={...randomCell(used),taken:false};hazards=Array.from({length:cfg===PRESETS.easy?2:4},(_,i)=>({...randomCell(used),kind:i%2?'wind':'puddle'}));decor=Array.from({length:34},()=>({x:Math.random(),y:Math.random(),type:world.decor[Math.floor(Math.random()*world.decor.length)],s:10+Math.random()*12,p:Math.random()*7}))}
function resize(){let r=wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0);cell=Math.max(18,Math.floor(Math.min((r.width-18)/cfg.cols,(r.height-18)/cfg.rows)));ox=Math.floor((r.width-cfg.cols*cell)/2);oy=Math.floor((r.height-cfg.rows*cell)/2);wall=Math.max(4,cell*.13);ball.r=Math.max(10,cell*.28);resetPositions()}
function at(obj){obj.px=ox+(obj.x+.5)*cell;obj.py=oy+(obj.y+.5)*cell}function resetPositions(){ball.x=ox+cell/2;ball.y=oy+cell/2;ball.vx=ball.vy=0;goal={x:ox+(cfg.cols-.5)*cell,y:oy+(cfg.rows-.5)*cell,r:Math.max(14,cell*.35),open:false};stars.forEach(at);at(keyItem);hazards.forEach(at)}
function updateUI(){let got=stars.filter(s=>s.taken).length;$('starCount').textContent=`${got} / ${stars.length}${keyItem?.taken?' + 🔑':''}`;goal.open=got===stars.length&&keyItem?.taken}
function newGame(){sync();cfg=PRESETS[$('difficulty').value];done=false;generate();place();resize();particles=[];running=true;updateUI()}
function current(){let x=Math.floor((ball.x-ox)/cell),y=Math.floor((ball.y-oy)/cell);return x>=0&&y>=0&&x<cfg.cols&&y<cfg.rows?maze[y][x]:null}
function collide(axis){let c=current();if(!c){resetPositions();return}let l=ox+c.x*cell,t=oy+c.y*cell,r=l+cell,b=t+cell,p=wall/2;if(axis==='x'){if(c.w.l&&ball.x-ball.r<l+p){ball.x=l+p+ball.r;ball.vx=Math.abs(ball.vx)*.18}if(c.w.r&&ball.x+ball.r>r-p){ball.x=r-p-ball.r;ball.vx=-Math.abs(ball.vx)*.18}}else{if(c.w.t&&ball.y-ball.r<t+p){ball.y=t+p+ball.r;ball.vy=Math.abs(ball.vy)*.18}if(c.w.b&&ball.y+ball.r>b-p){ball.y=b-p-ball.r;ball.vy=-Math.abs(ball.vy)*.18}}}
function burst(x,y,n=18){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.8)*180,life:1,type:['star','heart','flower'][Math.floor(Math.random()*3)]})}
function win(){done=true;running=false;save.level++;save.wins++;save.totalStars+=cfg.stars+1;saveGame(save);tone('win');burst(goal.x,goal.y,55);navigator.vibrate?.([50,30,90]);setTimeout(()=>showWin(),500)}
function showWin(){sync();overlay.innerHTML=`<div class="card"><canvas id="winHero" width="180" height="120"></canvas><h1>Dokázala jsi to!</h1><p>Hvězdičky i klíček jsou v bezpečí.<br><b>${nextReward()}</b></p><button id="again" class="button primary big">Další dobrodružství</button></div>`;overlay.classList.remove('hidden');drawHero($('winHero').getContext('2d'),hero,90,70,65,0);$('again').onclick=()=>{overlay.classList.add('hidden');newGame()}}
function nextReward(){let all=[...HEROES.map(h=>({name:h.name,need:h.need})),...WORLDS.map(w=>({name:w.name,need:w.need}))].filter(x=>x.need>save.totalStars).sort((a,b)=>a.need-b.need);return all[0]?`Do další odměny zbývá ${all[0].need-save.totalStars} hvězdiček.`:'Odemkla jsi všechny odměny!'}
function update(dt){dt=Math.min(.025,dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(!running||done)return;let slow=1;for(let h of hazards){let dist=Math.hypot(ball.x-h.px,ball.y-h.py);if(dist<cell*.48){if(h.kind==='puddle')slow=.55;else{ball.vx+=(h.x%2?.6:-.6)*cfg.accel*dt;ball.vy+=Math.sin(performance.now()/500)*cfg.accel*.18*dt}}}ball.vx+=tilt.x*cfg.accel*dt;ball.vy+=tilt.y*cfg.accel*dt;let friction=Math.pow(.984,dt*60);ball.vx*=friction*slow;ball.vy*=friction*slow;let speed=Math.hypot(ball.vx,ball.vy);if(speed>cfg.max){ball.vx=ball.vx/speed*cfg.max;ball.vy=ball.vy/speed*cfg.max}let steps=Math.max(1,Math.ceil(speed*dt/Math.max(3,ball.r*.6))),s=dt/steps;for(let i=0;i<steps;i++){ball.x+=ball.vx*s;collide('x');ball.y+=ball.vy*s;collide('y')}for(let star of stars)if(!star.taken&&Math.hypot(ball.x-star.px,ball.y-star.py)<cell*.48){star.taken=true;tone('star');burst(star.px,star.py);praise();navigator.vibrate?.(25);updateUI()}if(!keyItem.taken&&Math.hypot(ball.x-keyItem.px,ball.y-keyItem.py)<cell*.48){keyItem.taken=true;tone('key');burst(keyItem.px,keyItem.py);praise('Našla jsi klíček!');updateUI()}if(goal.open&&Math.hypot(ball.x-goal.x,ball.y-goal.y)<goal.r*.8)win()}
function drawMaze(){ctx.beginPath();ctx.lineWidth=wall+5;ctx.lineCap='round';ctx.strokeStyle=world.wall;for(let y=0;y<cfg.rows;y++)for(let x=0;x<cfg.cols;x++){let c=maze[y][x],x0=ox+x*cell,y0=oy+y*cell,x1=x0+cell,y1=y0+cell;if(c.w.t){ctx.moveTo(x0,y0);ctx.lineTo(x1,y0)}if(c.w.l){ctx.moveTo(x0,y0);ctx.lineTo(x0,y1)}if(x===cfg.cols-1&&c.w.r){ctx.moveTo(x1,y0);ctx.lineTo(x1,y1)}if(y===cfg.rows-1&&c.w.b){ctx.moveTo(x0,y1);ctx.lineTo(x1,y1)}}ctx.stroke();ctx.strokeStyle=world.trim;ctx.lineWidth=wall;ctx.stroke()}
function draw(){let r=canvas.getBoundingClientRect(),t=performance.now()/1000,g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,world.sky[0]);g.addColorStop(1,world.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);decor.forEach((d,i)=>drawDecor(ctx,d.type,(d.x*r.width+t*(i%3===0?5:0))%r.width,d.y*r.height+d.p*Math.sin(t*.7+i),d.s,t+d.p));ctx.fillStyle=world.ground;roundRect(ctx,ox,oy,cfg.cols*cell,cfg.rows*cell,18);ctx.fill();hazards.forEach(h=>{ctx.globalAlpha=.7;if(h.kind==='puddle'){ctx.fillStyle='#72c8e8';ctx.beginPath();ctx.ellipse(h.px,h.py,cell*.3,cell*.2,0,0,7);ctx.fill()}else drawDecor(ctx,'cloud',h.px,h.py,cell*.8,t);ctx.globalAlpha=1});drawMaze();stars.forEach(s=>{if(!s.taken)drawStar(ctx,s.px,s.py,cell*.27,t*1.5+s.p)});if(!keyItem.taken){ctx.fillStyle='#ffd33d';ctx.font=`${cell*.7}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('⚿',keyItem.px,keyItem.py)}ctx.globalAlpha=goal.open?1:.32;ctx.strokeStyle='#ff70b7';ctx.lineWidth=5;ctx.beginPath();ctx.arc(goal.x,goal.y,goal.r,Math.PI,0);ctx.stroke();ctx.strokeStyle='#ffd23f';ctx.beginPath();ctx.arc(goal.x,goal.y,goal.r*.68,Math.PI,0);ctx.stroke();ctx.globalAlpha=1;if(!goal.open){ctx.fillStyle='#76516f';ctx.font=`${goal.r}px sans-serif`;ctx.fillText('•',goal.x,goal.y)}drawHero(ctx,hero,ball.x,ball.y,ball.r*1.75,t);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);drawDecor(ctx,p.type,p.x,p.y,18,t)});ctx.globalAlpha=1}
function loop(now){update((now-last)/1000);last=now;draw();requestAnimationFrame(loop)}
async function sensors(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error();addEventListener('deviceorientation',orientation,true);$('status').textContent='Čekám na náklon…';setTimeout(()=>{if(!sensorSeen)$('status').textContent='Použij prst'},1700)}catch{$('status').textContent='Použij prst'}}
function orientation(e){if(e.beta==null||e.gamma==null)return;sensorSeen=true;$('status').textContent='Náklon funguje ✓';let g=e.gamma-cal.gamma,b=e.beta-cal.beta,a=screen.orientation?.angle??window.orientation??0,x=g,y=b;if(a===90){x=b;y=-g}else if(a===270||a===-90){x=-b;y=g}else if(a===180){x=-g;y=-b}raw={x,y};tilt.x+=(Math.max(-22,Math.min(22,x))/22-tilt.x)*.18;tilt.y+=(Math.max(-22,Math.min(22,y))/22-tilt.y)*.18}
function heroMenu(){let cards=HEROES.map(h=>`<button class="choice ${h.need>save.totalStars?'locked':''} ${h.id===hero.id?'selected':''}" data-id="${h.id}" ${h.need>save.totalStars?'disabled':''}><canvas width="80" height="65"></canvas><small>${h.need>save.totalStars?'⭐ '+h.need:h.name}</small></button>`).join('');overlay.innerHTML=`<div class="card"><h2>Vyber kamaráda</h2><div class="choice-grid">${cards}</div><button id="close" class="button primary">Hotovo</button></div>`;overlay.classList.remove('hidden');overlay.querySelectorAll('.choice').forEach((b,i)=>{drawHero(b.querySelector('canvas').getContext('2d'),HEROES[i],40,37,31,0);if(!b.disabled)b.onclick=()=>{save.hero=b.dataset.id;saveGame(save);sync();heroMenu()}});$('close').onclick=()=>overlay.classList.add('hidden')}
function album(){let heroes=HEROES.map(h=>`<div class="album-item">${save.totalStars>=h.need?'✓':'🔒'} ${h.name}<div class="meter"><span style="width:${Math.min(100,save.totalStars/h.need*100||100)}%"></span></div></div>`).join(''),worlds=WORLDS.map(w=>`<div class="album-item">${save.totalStars>=w.need?'✓':'🔒'} ${w.name}</div>`).join('');overlay.innerHTML=`<div class="card"><h2>Moje album</h2><p class="reward-line"><b>Hvězdičky</b><b>${save.totalStars}</b></p><p class="reward-line"><b>Dokončená dobrodružství</b><b>${save.wins}</b></p><div class="album-grid">${heroes}${worlds}</div><p>${nextReward()}</p><button id="close" class="button primary">Zpátky</button></div>`;overlay.classList.remove('hidden');$('close').onclick=()=>overlay.classList.add('hidden')}
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){tilt.x=Math.max(-1,Math.min(1,(e.clientX-drag.x)/65));tilt.y=Math.max(-1,Math.min(1,(e.clientY-drag.y)/65))}};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;tilt.x*=.15;tilt.y*=.15};
$('start').onclick=async()=>{await sensors();overlay.classList.add('hidden');newGame()};$('restart').onclick=newGame;$('difficulty').onchange=newGame;$('characters').onclick=heroMenu;$('album').onclick=album;$('calibrate').onclick=()=>{cal.beta+=raw.y;cal.gamma+=raw.x;raw={x:0,y:0};tilt={x:0,y:0};$('status').textContent='Náklon srovnán ✓'};addEventListener('resize',resize);sync();generate();place();resize();updateUI();drawHero($('heroPreview').getContext('2d'),hero,90,76,58,0);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');requestAnimationFrame(loop);
