const PORTRAIT=window.innerHeight>window.innerWidth;
const W=PORTRAIT?720:1280,H=PORTRAIT?1280:720,CELL=PORTRAIT?64:80,COLS=PORTRAIT?9:12,ROWS=PORTRAIT?15:7;
const OX=Math.round((W-COLS*CELL)/2),OY=PORTRAIT?170:105,STAR_COUNT=5;
const ui={stars:document.querySelector('#stars'),keys:document.querySelector('#keys'),message:document.querySelector('#message'),sensor:document.querySelector('#sensor-status'),intro:document.querySelector('#intro')};
let inputVector={x:0,y:0},tiltVector={x:0,y:0},sensorActive=false;
function flash(text){ui.message.textContent=text;ui.message.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>ui.message.classList.remove('show'),1100)}
function mulberry32(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function generateMaze(cols,rows,seed=Date.now()){const rnd=mulberry32(seed),cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({t:1,r:1,b:1,l:1,v:0})));let x=0,y=0,stack=[];cells[0][0].v=1;while(true){const n=[];if(y&&!cells[y-1][x].v)n.push([x,y-1,'t','b']);if(x<cols-1&&!cells[y][x+1].v)n.push([x+1,y,'r','l']);if(y<rows-1&&!cells[y+1][x].v)n.push([x,y+1,'b','t']);if(x&&!cells[y][x-1].v)n.push([x-1,y,'l','r']);if(n.length){const[nx,ny,a,b]=n[Math.floor(rnd()*n.length)];cells[y][x][a]=0;cells[ny][nx][b]=0;stack.push([x,y]);x=nx;y=ny;cells[y][x].v=1}else if(stack.length)[x,y]=stack.pop();else break}for(let i=0;i<Math.max(9,Math.floor(cols*rows*.08));i++){x=Math.floor(rnd()*cols);y=Math.floor(rnd()*rows);if(x<cols-1&&rnd()>.5){cells[y][x].r=0;cells[y][x+1].l=0}else if(y<rows-1){cells[y][x].b=0;cells[y+1][x].t=0}}return cells}
class GardenScene extends Phaser.Scene{
 constructor(){super('garden');this.won=false;this.collected=0;this.hasKey=false;this.gateOpened=false;this.butterflies=[]}
 create(){this.makeTextures();this.maze=generateMaze(COLS,ROWS);this.drawWorld();this.createObjects();this.createPlayer();this.createParticles();this.setupInput();this.cameras.main.fadeIn(600,255,255,255)}
 makeTextures(){const g=this.make.graphics({x:0,y:0,add:false});
  g.fillStyle(0x2e741f).fillRoundedRect(2,14,76,58,18);g.fillStyle(0x4d9d28).fillRoundedRect(3,8,74,58,18);g.fillStyle(0x70c83c).fillCircle(12,20,17).fillCircle(31,14,20).fillCircle(51,16,21).fillCircle(69,22,16);g.fillStyle(0x9be75c).fillCircle(19,12,6).fillCircle(43,10,7).fillCircle(63,17,5);g.fillStyle(0x3e8d27).fillCircle(24,29,7).fillCircle(56,31,8);g.lineStyle(3,0x225e1b).strokeRoundedRect(3,10,74,61,17);g.generateTexture('hedge',80,80);g.clear();
  g.fillStyle(0xffffff,.96).fillCircle(28,30,18).fillEllipse(46,38,50,30).fillCircle(57,24,16);g.fillStyle(0xdaf4ff,.8).fillEllipse(44,48,62,16);g.generateTexture('cloud',90,60);g.clear();
  g.fillStyle(0x7a4b2a).fillRoundedRect(30,35,18,38,6);g.fillStyle(0x2f7d2c).fillCircle(38,25,31);g.fillStyle(0x55ad3b).fillCircle(17,33,22).fillCircle(57,34,23).fillCircle(39,8,22);g.fillStyle(0x82d454).fillCircle(24,16,8).fillCircle(51,18,7);g.generateTexture('tree',78,78);g.clear();
  g.fillStyle(0x978f9d).fillEllipse(40,35,62,42);g.fillStyle(0xc8c5cc).fillEllipse(31,26,30,15);g.lineStyle(3,0x716b78).strokeEllipse(40,35,62,42);g.generateTexture('rock',80,60);g.clear();
  g.fillStyle(0xffffff).fillEllipse(42,49,56,36);g.fillStyle(0xf7c8e8).fillEllipse(22,37,23,33);g.fillStyle(0xffffff).fillCircle(58,27,25);g.fillStyle(0xff6ab4).fillTriangle(44,10,52,-12,60,11);g.fillStyle(0xffd046).fillTriangle(49,10,53,-8,58,11);g.fillStyle(0x6a3974).fillCircle(65,24,4);g.fillStyle(0xffffff).fillCircle(66,23,1.5);g.fillStyle(0xed72aa).fillCircle(70,35,4);g.fillStyle(0x9b48bd).fillEllipse(31,35,12,27);g.fillStyle(0xff6cab).fillEllipse(24,35,9,22);g.lineStyle(4,0x6a3974).strokeEllipse(16,33,23,27);g.fillStyle(0x8c3cab).fillRoundedRect(23,62,9,14,4).fillRoundedRect(51,62,9,14,4);g.fillStyle(0xffd5ea).fillCircle(52,37,3);g.generateTexture('lili',92,82);g.clear();
  g.fillStyle(0xffd52f);g.lineStyle(5,0xff9600);const pts=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?16:32;pts.push(new Phaser.Geom.Point(34+Math.cos(a)*r,34+Math.sin(a)*r))}g.fillPoints(pts,true);g.strokePoints(pts,true);g.fillStyle(0xffffff,.9).fillCircle(24,19,5);g.generateTexture('star',68,68);g.clear();
  g.lineStyle(10,0xf3a900).strokeCircle(24,24,15);g.fillStyle(0xffd847).fillRoundedRect(34,20,34,9,4).fillRoundedRect(56,28,8,17,2).fillRoundedRect(45,28,8,12,2);g.fillStyle(0xfff2a0).fillCircle(18,18,4);g.generateTexture('key',76,52);g.clear();
  const colors=[0xff4f7d,0xff9d2f,0xffdf3d,0x65d454,0x42b9ff,0x7b54df];for(let i=0;i<6;i++){g.lineStyle(11,colors[i]).beginPath().arc(70,73,58-i*9,Math.PI,Math.PI*2).strokePath()}g.fillStyle(0xffffff,.97).fillRoundedRect(8,68,124,23,11);g.fillStyle(0xffd54f).fillCircle(17,75,10).fillCircle(123,75,10);g.generateTexture('gate',140,96);g.clear();
  g.fillStyle(0x4cb7e8,.82).fillEllipse(40,22,68,34);g.fillStyle(0x9ee7ff,.65).fillEllipse(32,17,40,12);g.lineStyle(3,0xc6f5ff).strokeEllipse(40,22,68,34);g.generateTexture('puddle',80,45);g.clear();
  g.fillStyle(0xff68c3).fillEllipse(17,18,22,28).fillEllipse(43,18,22,28);g.fillStyle(0x6a3b72).fillRoundedRect(27,8,6,28,3);g.fillStyle(0xffffff,.7).fillCircle(13,12,4).fillCircle(47,12,4);g.generateTexture('butterfly',60,40);g.clear();
  g.fillStyle(0xff554e).fillCircle(20,15,12);g.fillStyle(0xffffff).fillCircle(16,13,2).fillCircle(23,18,2);g.fillStyle(0xf8e1c8).fillRoundedRect(16,22,8,18,3);g.generateTexture('mushroom',40,42);g.destroy()}
 drawWorld(){const bg=this.add.graphics();const horizon=PORTRAIT?350:300;bg.fillGradientStyle(0x43c3ff,0x43c3ff,0xcff5ff,0xcff5ff).fillRect(0,0,W,H);bg.fillStyle(0xfff3a3,.35).fillCircle(W*.78,100,75);bg.fillStyle(0x9bdc72).fillRect(0,horizon,W,H-horizon);bg.fillStyle(0x6fbc4c).fillEllipse(W*.16,horizon+55,W*.8,230).fillEllipse(W*.82,horizon+45,W*.85,240);for(let i=0;i<Math.ceil(W/115);i++)this.add.image(45+i*115,72+Math.sin(i*1.7)*20,'cloud').setAlpha(.7).setScale(.78).setDepth(0);
  for(let i=0;i<(PORTRAIT?9:13);i++){const x=Phaser.Math.Between(25,W-25),y=Phaser.Math.Between(horizon-35,horizon+80);this.add.image(x,y,'tree').setScale(Phaser.Math.FloatBetween(.75,1.2)).setDepth(1)}
  const ground=this.add.graphics().setDepth(2);ground.fillStyle(0xcfee8b).fillRoundedRect(OX-22,OY-22,COLS*CELL+44,ROWS*CELL+44,30);ground.lineStyle(10,0xffffff,.62).strokeRoundedRect(OX-22,OY-22,COLS*CELL+44,ROWS*CELL+44,30);ground.lineStyle(3,0xa6d563,.7);for(let y=OY+CELL/2;y<OY+ROWS*CELL;y+=CELL)ground.lineBetween(OX+8,y,OX+COLS*CELL-8,y);for(let x=OX+CELL/2;x<OX+COLS*CELL;x+=CELL)ground.lineBetween(x,OY+8,x,OY+ROWS*CELL-8);
  this.walls=this.physics.add.staticGroup();const thick=Math.max(20,CELL*.31);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const c=this.maze[y][x],cx=OX+x*CELL,cy=OY+y*CELL;if(c.t)this.wall(cx+CELL/2,cy,CELL,thick);if(c.l)this.wall(cx,cy+CELL/2,thick,CELL);if(x===COLS-1&&c.r)this.wall(cx+CELL,cy+CELL/2,thick,CELL);if(y===ROWS-1&&c.b)this.wall(cx+CELL/2,cy+CELL,CELL,thick)}
  for(let i=0;i<(PORTRAIT?48:58);i++){const x=Phaser.Math.Between(15,W-15),y=Phaser.Math.Between(horizon,H-10);if(x>OX-30&&x<OX+COLS*CELL+30&&y>OY-30&&y<OY+ROWS*CELL+30)continue;const r=Math.random();if(r<.62)this.flower(x,y,Phaser.Math.RND.pick([0xff67af,0xffd643,0x766ee8,0xffffff,0x46b6ff]));else if(r<.8)this.add.image(x,y,'rock').setScale(Phaser.Math.FloatBetween(.28,.5)).setDepth(2);else this.add.image(x,y,'mushroom').setScale(Phaser.Math.FloatBetween(.5,.8)).setDepth(3)}
  for(let i=0;i<(PORTRAIT?5:7);i++){const b=this.add.image(Phaser.Math.Between(40,W-40),Phaser.Math.Between(horizon,H-80),'butterfly').setScale(.42).setDepth(8);b.baseY=b.y;b.speed=Phaser.Math.FloatBetween(.7,1.4);b.phase=Math.random()*6;this.butterflies.push(b)}}
 wall(x,y,w,h){const s=this.walls.create(x,y,'hedge').setDisplaySize(w,h).refreshBody().setDepth(6);s.setTint(Phaser.Display.Color.GetColor(245+Phaser.Math.Between(0,10),255,245))}
 flower(x,y,color){const g=this.add.graphics().setDepth(3);g.lineStyle(3,0x3a8e2f).lineBetween(x,y,x,y-14);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;g.fillStyle(color).fillCircle(x+Math.cos(a)*7,y-16+Math.sin(a)*7,5)}g.fillStyle(0xffc62d).fillCircle(x,y-16,4)}
 randomOpen(used){let x,y,k;do{x=Phaser.Math.Between(0,COLS-1);y=Phaser.Math.Between(0,ROWS-1);k=`${x},${y}`}while(used.has(k));used.add(k);return{x:OX+x*CELL+CELL/2,y:OY+y*CELL+CELL/2}}
 createObjects(){const used=new Set(['0,0',`${COLS-1},${ROWS-1}`]);this.stars=this.physics.add.group();for(let i=0;i<STAR_COUNT;i++){const p=this.randomOpen(used),s=this.stars.create(p.x,p.y,'star').setScale(PORTRAIT?.5:.64).setDepth(9);this.tweens.add({targets:s,scale:PORTRAIT?.62:.78,angle:360,duration:1500+i*100,yoyo:true,repeat:-1,ease:'Sine.inOut'})}const kp=this.randomOpen(used);this.key=this.physics.add.image(kp.x,kp.y,'key').setScale(PORTRAIT?.58:.7).setDepth(9);this.tweens.add({targets:this.key,y:this.key.y-8,angle:{from:-4,to:4},duration:900,yoyo:true,repeat:-1});this.gate=this.physics.add.staticImage(OX+(COLS-.5)*CELL,OY+(ROWS-.43)*CELL,'gate').setScale(PORTRAIT?.72:1).setDepth(8).setAlpha(.35);this.puddles=this.physics.add.staticGroup();for(let i=0;i<3;i++){const p=this.randomOpen(used);const puddle=this.puddles.create(p.x,p.y,'puddle').setScale(PORTRAIT?.72:1).setDepth(4);puddle.refreshBody();this.tweens.add({targets:puddle,alpha:{from:.72,to:1},duration:1100+i*120,yoyo:true,repeat:-1})}}
 createPlayer(){this.player=this.physics.add.image(OX+CELL/2,OY+CELL/2,'lili').setScale(PORTRAIT?.8:1).setDepth(12);this.player.setCircle(24,20,18).setCollideWorldBounds(true);this.player.body.setMaxVelocity(PORTRAIT?220:260);this.player.body.setDrag(PORTRAIT?390:430);this.physics.add.collider(this.player,this.walls);this.physics.add.overlap(this.player,this.stars,(_,s)=>this.collectStar(s));this.physics.add.overlap(this.player,this.key,()=>this.collectKey());this.physics.add.overlap(this.player,this.gate,()=>this.tryWin());this.physics.add.overlap(this.player,this.puddles,()=>this.player.body.velocity.scale(.96));this.tweens.add({targets:this.player,scaleY:PORTRAIT?.77:.96,duration:270,yoyo:true,repeat:-1,ease:'Sine.inOut'});this.playerGlow=this.add.circle(this.player.x,this.player.y,28,0xffb7e6,.22).setDepth(11);this.tweens.add({targets:this.playerGlow,scale:1.35,alpha:.08,duration:850,yoyo:true,repeat:-1})}
 createParticles(){this.sparkles=this.add.particles(0,0,'star',{speed:{min:45,max:155},scale:{start:.22,end:0},lifespan:750,gravityY:70,emitting:false}).setDepth(20)}
 collectStar(s){s.disableBody(true,true);this.collected++;ui.stars.textContent=`${this.collected} / ${STAR_COUNT}`;this.sparkles.emitParticleAt(s.x,s.y,14);this.cameras.main.shake(90,.002);flash(Phaser.Math.RND.pick(['Skvělé!','Paráda!','Jsi šikulka!','Hvězdička je tvoje!']));this.updateGate()}
 collectKey(){if(this.hasKey)return;this.hasKey=true;ui.keys.textContent='1 / 1';this.sparkles.emitParticleAt(this.key.x,this.key.y,20);this.key.disableBody(true,true);flash('Našla jsi klíček!');this.updateGate()}
 updateGate(){if(this.gateOpened||!this.hasKey||this.collected!==STAR_COUNT)return;this.gateOpened=true;this.gate.setAlpha(1);this.tweens.add({targets:this.gate,scale:this.gate.scale*1.09,duration:650,yoyo:true,repeat:-1,ease:'Sine.inOut'});this.sparkles.emitParticleAt(this.gate.x,this.gate.y,30);flash('Duhová brána je otevřená!')}
 tryWin(){if(this.won||!this.gateOpened)return;this.won=true;this.player.setVelocity(0);this.sparkles.emitParticleAt(this.gate.x,this.gate.y,55);this.cameras.main.flash(700,255,245,180);flash('Dokázala jsi to!');this.time.delayedCall(1400,()=>this.scene.restart())}
 setupInput(){this.cursors=this.input.keyboard?.createCursorKeys();document.querySelector('#restart').onclick=()=>this.scene.restart()}
 update(){const t=this.time.now/1000;for(const b of this.butterflies){b.x+=b.speed*.35;b.y=b.baseY+Math.sin(t*2+b.phase)*10;b.scaleX=.42*(.75+.25*Math.sin(t*7+b.phase));if(b.x>W+30)b.x=-30}if(this.playerGlow){this.playerGlow.x=this.player.x;this.playerGlow.y=this.player.y+6}if(this.won)return;const keyX=(this.cursors?.left.isDown?-1:0)+(this.cursors?.right.isDown?1:0),keyY=(this.cursors?.up.isDown?-1:0)+(this.cursors?.down.isDown?1:0);let x=inputVector.x+tiltVector.x+keyX,y=inputVector.y+tiltVector.y+keyY;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}this.player.setAcceleration(x*(PORTRAIT?520:620),y*(PORTRAIT?520:620));if(Math.abs(x)>.08)this.player.setFlipX(x<0);this.player.angle=Math.abs(x)+Math.abs(y)>.1?Math.sin(this.time.now/95)*2:0}}
const config={type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#6ed3ff',render:{antialias:true,pixelArt:false,roundPixels:false},physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:GardenScene};new Phaser.Game(config);
document.querySelector('#play').onclick=async()=>{ui.intro.classList.add('hidden');try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')await DeviceOrientationEvent.requestPermission()}catch{}window.addEventListener('deviceorientation',e=>{if(e.beta==null||e.gamma==null)return;sensorActive=true;ui.sensor.textContent='Náklon funguje ✓';tiltVector.x=Phaser.Math.Clamp(e.gamma/22,-1,1);tiltVector.y=Phaser.Math.Clamp((e.beta-35)/22,-1,1)},true)};
const joy=document.querySelector('#joystick'),knob=document.querySelector('#joystick-knob');let pointer=null;function moveJoy(e){if(pointer!==e.pointerId)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.32,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len),x=dx*k,y=dy*k;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;inputVector={x:x/max,y:y/max}}joy.addEventListener('pointerdown',e=>{pointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener('pointermove',moveJoy);function release(e){if(pointer!==e.pointerId)return;pointer=null;inputVector={x:0,y:0};knob.style.transform='translate(-50%,-50%)'}joy.addEventListener('pointerup',release);joy.addEventListener('pointercancel',release);setTimeout(()=>{if(!sensorActive)ui.sensor.textContent='Použij joystick nebo šipky'},2200);let lastPortrait=PORTRAIT;window.addEventListener('orientationchange',()=>setTimeout(()=>{if((innerHeight>innerWidth)!==lastPortrait)location.reload()},250));