const W=1280,H=720,CELL=80,COLS=12,ROWS=7,OX=160,OY=105;
const STAR_COUNT=5;
const ui={stars:document.querySelector('#stars'),keys:document.querySelector('#keys'),message:document.querySelector('#message'),sensor:document.querySelector('#sensor-status'),intro:document.querySelector('#intro')};
let inputVector={x:0,y:0},tiltVector={x:0,y:0},sensorActive=false;

function flash(text){ui.message.textContent=text;ui.message.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>ui.message.classList.remove('show'),1000)}
function mulberry32(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function generateMaze(cols,rows,seed=Date.now()){const rnd=mulberry32(seed),cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({t:1,r:1,b:1,l:1,v:0})));let x=0,y=0,stack=[];cells[0][0].v=1;while(true){const n=[];if(y>0&&!cells[y-1][x].v)n.push([x,y-1,'t','b']);if(x<cols-1&&!cells[y][x+1].v)n.push([x+1,y,'r','l']);if(y<rows-1&&!cells[y+1][x].v)n.push([x,y+1,'b','t']);if(x>0&&!cells[y][x-1].v)n.push([x-1,y,'l','r']);if(n.length){const [nx,ny,a,b]=n[Math.floor(rnd()*n.length)];cells[y][x][a]=0;cells[ny][nx][b]=0;stack.push([x,y]);x=nx;y=ny;cells[y][x].v=1}else if(stack.length){[x,y]=stack.pop()}else break}for(let i=0;i<9;i++){x=Math.floor(rnd()*cols);y=Math.floor(rnd()*rows);if(x<cols-1&&rnd()>.5){cells[y][x].r=0;cells[y][x+1].l=0}else if(y<rows-1){cells[y][x].b=0;cells[y+1][x].t=0}}return cells}

class GardenScene extends Phaser.Scene{
  constructor(){super('garden');this.won=false;this.collected=0;this.hasKey=false}
  create(){this.makeTextures();this.maze=generateMaze(COLS,ROWS);this.drawWorld();this.createObjects();this.createPlayer();this.createParticles();this.setupInput();this.cameras.main.fadeIn(500,255,255,255)}
  makeTextures(){
    const g=this.make.graphics({x:0,y:0,add:false});
    g.fillStyle(0x55a82c).fillRoundedRect(0,8,80,64,18);g.fillStyle(0x78cc3d).fillCircle(16,20,18).fillCircle(40,15,22).fillCircle(66,22,17);g.fillStyle(0xa8e95e).fillCircle(25,14,7).fillCircle(54,20,6);g.lineStyle(4,0x2f761f).strokeRoundedRect(2,10,76,60,17);g.generateTexture('hedge',80,80);g.clear();
    g.fillStyle(0xffffff).fillCircle(30,31,19).fillEllipse(45,38,42,30).fillCircle(53,23,15);g.fillStyle(0xe9f7ff).fillEllipse(40,48,58,18);g.generateTexture('cloud',80,60);g.clear();
    g.fillStyle(0xffffff).fillEllipse(42,48,52,35);g.fillStyle(0xffd2ed).fillEllipse(22,35,23,32);g.fillStyle(0xffffff).fillCircle(56,27,24);g.fillStyle(0xff70b9).fillTriangle(43,8,51,-12,58,11);g.fillStyle(0xffcc35).fillTriangle(48,10,52,-8,57,11);g.fillStyle(0x65366f).fillCircle(64,25,3);g.fillStyle(0xffffff).fillCircle(65,24,1);g.fillStyle(0xe454a2).fillCircle(72,31,3);g.fillStyle(0xb04bc0).fillEllipse(31,35,12,26);g.fillStyle(0xff62a9).fillEllipse(24,34,8,22);g.lineStyle(4,0x6b3d75).strokeEllipse(16,32,22,26);g.fillStyle(0x913db4).fillRoundedRect(23,60,9,14,4).fillRoundedRect(50,60,9,14,4);g.generateTexture('lili',90,80);g.clear();
    g.fillStyle(0xffd22f);g.lineStyle(4,0xff9d00);const pts=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?16:32;pts.push(new Phaser.Geom.Point(34+Math.cos(a)*r,34+Math.sin(a)*r))}g.fillPoints(pts,true);g.strokePoints(pts,true);g.fillStyle(0xffffff,0.8).fillCircle(25,20,5);g.generateTexture('star',68,68);g.clear();
    g.lineStyle(10,0xffb400).strokeCircle(24,24,15);g.fillStyle(0xffd33d).fillRoundedRect(34,20,34,9,4).fillRoundedRect(56,28,8,17,2).fillRoundedRect(45,28,8,12,2);g.generateTexture('key',76,52);g.clear();
    const colors=[0xff4b73,0xff9d2e,0xffdf39,0x65d454,0x47b9ff,0x7955df];for(let i=0;i<6;i++){g.lineStyle(10,colors[i]).beginPath().arc(70,72,58-i*9,Math.PI,Math.PI*2).strokePath()}g.fillStyle(0xffffff,0.95).fillRoundedRect(8,68,124,22,11);g.generateTexture('gate',140,95);g.clear();
    g.fillStyle(0x59b8ec,0.85).fillEllipse(40,22,68,34);g.lineStyle(3,0xb7ecff).strokeEllipse(40,22,68,34);g.generateTexture('puddle',80,45);g.destroy()
  }
  drawWorld(){
    const bg=this.add.graphics();bg.fillGradientStyle(0x50caff,0x50caff,0xd6f4ff,0xd6f4ff).fillRect(0,0,W,H);bg.fillStyle(0x9edb68).fillRect(0,310,W,410);bg.fillStyle(0x78be49).fillEllipse(250,360,650,190).fillEllipse(1000,355,760,210);
    for(let i=0;i<14;i++)this.add.image(40+i*100,80+Math.sin(i)*18,'cloud').setAlpha(.7).setScale(.75).setDepth(0);
    const ground=this.add.graphics().setDepth(1);ground.fillStyle(0xdaf49a).fillRoundedRect(OX-18,OY-18,COLS*CELL+36,ROWS*CELL+36,28);ground.lineStyle(8,0xffffff,0.5).strokeRoundedRect(OX-18,OY-18,COLS*CELL+36,ROWS*CELL+36,28);
    this.walls=this.physics.add.staticGroup();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const c=this.maze[y][x],cx=OX+x*CELL,cy=OY+y*CELL;if(c.t)this.wall(cx+CELL/2,cy,80,26);if(c.l)this.wall(cx,cy+CELL/2,26,80);if(x===COLS-1&&c.r)this.wall(cx+CELL,cy+CELL/2,26,80);if(y===ROWS-1&&c.b)this.wall(cx+CELL/2,cy+CELL,80,26)}
    for(let i=0;i<50;i++){const x=Phaser.Math.Between(20,W-20),y=Phaser.Math.Between(315,H-10);if(x>OX-25&&x<OX+COLS*CELL+25&&y>OY-25&&y<OY+ROWS*CELL+25)continue;this.flower(x,y,Phaser.Math.RND.pick([0xff67af,0xffd643,0x766ee8,0xffffff]))}
  }
  wall(x,y,w,h){const body=this.walls.create(x,y,'hedge');body.setDisplaySize(w,h).refreshBody().setDepth(5)}
  flower(x,y,color){const g=this.add.graphics().setDepth(2);g.lineStyle(3,0x3c972f).lineBetween(x,y,x,y-13);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;g.fillStyle(color).fillCircle(x+Math.cos(a)*7,y-15+Math.sin(a)*7,5)}g.fillStyle(0xffc62d).fillCircle(x,y-15,4)}
  randomOpen(used){let x,y,k;do{x=Phaser.Math.Between(0,COLS-1);y=Phaser.Math.Between(0,ROWS-1);k=`${x},${y}`}while(used.has(k));used.add(k);return{x:OX+x*CELL+CELL/2,y:OY+y*CELL+CELL/2}}
  createObjects(){const used=new Set(['0,0',`${COLS-1},${ROWS-1}`]);this.stars=this.physics.add.group();for(let i=0;i<STAR_COUNT;i++){const p=this.randomOpen(used),s=this.stars.create(p.x,p.y,'star').setScale(.65).setDepth(7);this.tweens.add({targets:s,scale:.78,angle:360,duration:1400+i*90,yoyo:true,repeat:-1,ease:'Sine.inOut'})}const kp=this.randomOpen(used);this.key=this.physics.add.image(kp.x,kp.y,'key').setScale(.7).setDepth(7);this.tweens.add({targets:this.key,y:this.key.y-8,duration:900,yoyo:true,repeat:-1});this.gate=this.physics.add.staticImage(OX+(COLS-.5)*CELL,OY+(ROWS-.43)*CELL,'gate').setDepth(6).setAlpha(.35);this.puddles=this.physics.add.staticGroup();for(let i=0;i<3;i++){const p=this.randomOpen(used);this.puddles.create(p.x,p.y,'puddle').setDepth(3).refreshBody()}}
  createPlayer(){this.player=this.physics.add.image(OX+CELL/2,OY+CELL/2,'lili').setDepth(10).setCircle(24,20,18).setCollideWorldBounds(true);this.player.body.setMaxVelocity(260);this.player.body.setDrag(430);this.physics.add.collider(this.player,this.walls);this.physics.add.overlap(this.player,this.stars,(_,s)=>this.collectStar(s));this.physics.add.overlap(this.player,this.key,()=>this.collectKey());this.physics.add.overlap(this.player,this.gate,()=>this.tryWin());this.physics.add.overlap(this.player,this.puddles,()=>this.player.body.velocity.scale(.96));this.tweens.add({targets:this.player,scaleY:.96,duration:280,yoyo:true,repeat:-1})}
  createParticles(){this.sparkles=this.add.particles(0,0,'star',{speed:{min:45,max:150},scale:{start:.22,end:0},lifespan:700,gravityY:80,emitting:false}).setDepth(20)}
  collectStar(s){s.disableBody(true,true);this.collected++;ui.stars.textContent=`${this.collected} / ${STAR_COUNT}`;this.sparkles.emitParticleAt(s.x,s.y,12);flash(Phaser.Math.RND.pick(['Skvělé!','Paráda!','Jsi šikulka!','Hvězdička je tvoje!']))}
  collectKey(){if(this.hasKey)return;this.hasKey=true;ui.keys.textContent='1 / 1';this.sparkles.emitParticleAt(this.key.x,this.key.y,18);this.key.disableBody(true,true);flash('Našla jsi klíček!');this.updateGate()}
  updateGate(){if(this.hasKey&&this.collected===STAR_COUNT){this.gate.setAlpha(1);this.tweens.add({targets:this.gate,scale:1.08,duration:650,yoyo:true,repeat:-1});flash('Duhová brána je otevřená!')}}
  tryWin(){if(this.won||!this.hasKey||this.collected<STAR_COUNT)return;this.won=true;this.player.setVelocity(0);this.sparkles.emitParticleAt(this.gate.x,this.gate.y,40);this.cameras.main.flash(700,255,245,180);flash('Dokázala jsi to!');this.time.delayedCall(1300,()=>this.scene.restart())}
  setupInput(){this.cursors=this.input.keyboard?.createCursorKeys();document.querySelector('#restart').onclick=()=>this.scene.restart()}
  update(){if(this.won)return;const keyX=(this.cursors?.left.isDown?-1:0)+(this.cursors?.right.isDown?1:0),keyY=(this.cursors?.up.isDown?-1:0)+(this.cursors?.down.isDown?1:0);let x=inputVector.x+tiltVector.x+keyX,y=inputVector.y+tiltVector.y+keyY;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len}this.player.setAcceleration(x*620,y*620);if(Math.abs(x)>.08)this.player.setFlipX(x<0);if(Math.abs(x)+Math.abs(y)>.1)this.player.angle=Math.sin(this.time.now/95)*2;else this.player.angle=0;this.updateGate()}
}

const config={type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#6ed3ff',physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:GardenScene};
const game=new Phaser.Game(config);

document.querySelector('#play').onclick=async()=>{ui.intro.classList.add('hidden');try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')await DeviceOrientationEvent.requestPermission()}catch{}window.addEventListener('deviceorientation',e=>{if(e.beta==null||e.gamma==null)return;sensorActive=true;ui.sensor.textContent='Náklon funguje ✓';tiltVector.x=Phaser.Math.Clamp(e.gamma/22,-1,1);tiltVector.y=Phaser.Math.Clamp((e.beta-35)/22,-1,1)},true)};

const joy=document.querySelector('#joystick'),knob=document.querySelector('#joystick-knob');let pointer=null;
function moveJoy(e){if(pointer!==e.pointerId)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.32,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len),x=dx*k,y=dy*k;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;inputVector={x:x/max,y:y/max}}
joy.addEventListener('pointerdown',e=>{pointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener('pointermove',moveJoy);function release(e){if(pointer!==e.pointerId)return;pointer=null;inputVector={x:0,y:0};knob.style.transform='translate(-50%,-50%)'}joy.addEventListener('pointerup',release);joy.addEventListener('pointercancel',release);
setTimeout(()=>{if(!sensorActive)ui.sensor.textContent='Použij joystick nebo šipky'},2200);